// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: energy.sql

package dbgen

import (
	"context"
)

const energyFindById = `-- name: EnergyFindById :one
SELECT id, name, image_url, description, regulation, expansion, created_at, updated_at
FROM energies
WHERE id = ?
`

func (q *Queries) EnergyFindById(ctx context.Context, id int64) (Energy, error) {
	row := q.db.QueryRowContext(ctx, energyFindById, id)
	var i Energy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ImageUrl,
		&i.Description,
		&i.Regulation,
		&i.Expansion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
