// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package dbgen

import (
	"database/sql"
	"time"
)

type CardType struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Deck struct {
	ID             int64          `json:"id"`
	Name           string         `json:"name"`
	Description    sql.NullString `json:"description"`
	MainCardID     sql.NullInt64  `json:"main_card_id"`
	MainCardTypeID sql.NullInt64  `json:"main_card_type_id"`
	SubCardID      sql.NullInt64  `json:"sub_card_id"`
	SubCardTypeID  sql.NullInt64  `json:"sub_card_type_id"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type DeckCard struct {
	ID         int64     `json:"id"`
	DeckID     int64     `json:"deck_id"`
	CardID     int64     `json:"card_id"`
	CardTypeID int64     `json:"card_type_id"`
	Quantity   int32     `json:"quantity"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type Energy struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	ImageUrl    string    `json:"image_url"`
	Description string    `json:"description"`
	Regulation  string    `json:"regulation"`
	Expansion   string    `json:"expansion"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Pokemon struct {
	ID                 int64          `json:"id"`
	Name               string         `json:"name"`
	EnergyType         string         `json:"energy_type"`
	ImageUrl           string         `json:"image_url"`
	Hp                 int64          `json:"hp"`
	Ability            sql.NullString `json:"ability"`
	AbilityDescription sql.NullString `json:"ability_description"`
	Regulation         string         `json:"regulation"`
	Expansion          string         `json:"expansion"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

type PokemonAttack struct {
	ID             int64          `json:"id"`
	PokemonID      int64          `json:"pokemon_id"`
	Name           string         `json:"name"`
	RequiredEnergy string         `json:"required_energy"`
	Damage         sql.NullString `json:"damage"`
	Description    sql.NullString `json:"description"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type Trainer struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	TrainerType string    `json:"trainer_type"`
	ImageUrl    string    `json:"image_url"`
	Description string    `json:"description"`
	Regulation  string    `json:"regulation"`
	Expansion   string    `json:"expansion"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
