// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package dbgen

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateDeck(ctx context.Context, arg CreateDeckParams) (sql.Result, error)
	CreateDeckCard(ctx context.Context, arg CreateDeckCardParams) (sql.Result, error)
	DeleteDeck(ctx context.Context, id int64) error
	DeleteDeckCardsByDeckId(ctx context.Context, deckID int64) error
	EnergyFindById(ctx context.Context, id int64) (Energy, error)
	FindALl(ctx context.Context) ([]Deck, error)
	FindDeckById(ctx context.Context, id int64) (Deck, error)
	FindDeckCardsByDeckId(ctx context.Context, deckID int64) ([]DeckCard, error)
	PokemonAttackFindByPokemonId(ctx context.Context, pokemonID int64) ([]PokemonAttack, error)
	PokemonFindById(ctx context.Context, id int64) (Pokemon, error)
	TrainerFindById(ctx context.Context, id int64) (Trainer, error)
	UpdateDeck(ctx context.Context, arg UpdateDeckParams) error
}

var _ Querier = (*Queries)(nil)
