### 検索API
http://localhost:8080/v1/cards/search?q=炎

### カード詳細API(ポケモン)
http://localhost:8080/v1/cards/detail/pokemon/47122

### カード詳細API(トレーナー)
http://localhost:8080/v1/cards/detail/trainer/46802

### カード詳細API(エネルギー)
http://localhost:8080/v1/cards/detail/energy/27973

### デッキ作成API
POST http://localhost:8080/v1/decks/create 
Content-Type: application/json

{
    "name": "サーナイト",
    "description": "CL宮城2025 準優勝",
    "main_card": {
        "id": 42574,
        "category": "pokemon"
    },
    "sub_card": {
        "id": 47041,
        "category": "pokemon"
    },
    "cards": [
        {
            "id": 42572,
            "category": "pokemon",
            "quantity": 3
        },
        {
            "id": 42573,
            "category": "pokemon",
            "quantity": 2
        },
        {
            "id": 42574,
            "category": "pokemon",
            "quantity": 3
        },
        {
            "id": 47041,
            "category": "pokemon",
            "quantity": 1
        },
        {
            "id": 43472,
            "category": "pokemon",
            "quantity": 1         
        },
        {
            "id": 45746,
            "category": "pokemon",
            "quantity": 3
        },
        {
            "id": 44278,
            "category": "pokemon",
            "quantity": 1
        },
        {
            "id": 45913,
            "category": "pokemon",
            "quantity": 1
        },
        {
            "id": 43272,
            "category": "pokemon",
            "quantity": 1
        },
        {
            "id": 46662,
            "category": "pokemon",
            "quantity": 2
        },
        {
            "id": 47281,
            "category": "trainer",
            "quantity": 1
        },
        {
            "id": 33119,
            "category": "trainer",
            "quantity": 3
        },
        {
            "id": 27615,
            "category": "trainer",
            "quantity": 3
        },
        {
            "id": 25395,
            "category": "trainer",
            "quantity": 3
        },
        {
            "id": 44306,
            "category": "trainer",
            "quantity": 2
        },
        {
            "id": 45931,
            "category": "trainer",
            "quantity": 3
        },
        {
            "id": 34175,
            "category": "trainer",
            "quantity": 2
        },
        {
            "id": 45783,
            "category": "trainer",
            "quantity": 1
        },
        {
            "id": 43203,
            "category": "trainer",
            "quantity": 3
        },
        {
            "id": 43205,
            "category": "trainer",
            "quantity": 4
        },
        {
            "id": 44064,
            "category": "trainer",
            "quantity": 3
        },
        {
            "id": 45215,
            "category": "trainer",
            "quantity": 2
        },
        {
            "id": 43035,
            "category": "trainer",
            "quantity": 2 
        },
        {
            "id": 30043,
            "category": "energy",
            "quantity": 3
        },
        {
            "id": 28363,
            "category": "energy",
            "quantity": 7
        }
    ]
}

### デッキ一覧API
GET http://localhost:8080/v1/decks
Content-Type: application/json

### デッキ詳細API
GET http://localhost:8080/v1/decks/detail/1
Content-Type: application/json

### デッキ編集API
POST http://localhost:8080/v1/decks/edit/1
Content-Type: application/json

{
    "name": "テストデッキ",
    "description": "テストデッキの説明",
    "main_card": {
        "id": 42261,
        "category": "pokemon"
    },
    "sub_card": {
        "id": 28017,
        "category": "trainer"
    },
    "cards": [
        {
            "id": 42261,
            "category": "pokemon",
            "quantity": 4
        },
        {
            "id": 28017,
            "category": "trainer",
            "quantity": 4
        },
        {
            "id": 46299,
            "category": "energy",
            "quantity": 52
        }
    ]
}

### デッキ削除API
DELETE http://localhost:8080/v1/decks/delete/1
Content-Type: application/json

